# Etapa 3 - Transformação dos Dados

In [16]:
import pandas as pd
import pandera as pa

In [17]:
#Criação do dataframe e checagem dos dados
valores_ausentes = "00/01/1900"
df = pd.read_csv("93f4e8c2-430f-4142-86b3-96dab4905b4e.csv", parse_dates=['data_inicio_primeiros_sintomas','data_notificacao','data_obito'], na_values=valores_ausentes)
df

,_id,sexo,idade,raca,etnia,morbidades_previas,outras_morbidades_previas,evolucao,data_inicio_primeiros_sintomas,data_notificacao,data_obito,classificacao_final
0,1,Masculino,9 meses,Ignorado,NaN,Doenças Respiratórias Crônicas,NaN,INTERNADO LEITO DE ISOLAMENTO,2021-02-24,2021-03-02,NaT,DESCARTADO
1,2,Feminino,46,Branca,NaN,NaN,NaN,INTERNADO LEITO DE ISOLAMENTO,2021-02-28,2021-03-03,NaT,EM ANÁLISE
2,3,Masculino,78,Branca,NaN,"Doenças Cardíacas ou Vasculares, Doença Hepáti...",NaN,ÓBITO,2021-01-06,2021-01-08,2021-01-26,CONFIRMADO
3,4,Feminino,62,Parda,NaN,NaN,NaN,INTERNADO LEITO DE ISOLAMENTO,2021-02-23,2021-03-02,NaT,EM ANÁLISE
4,5,Masculino,26,Parda,NaN,NaN,NaN,INTERNADO LEITO DE ISOLAMENTO,2021-02-24,2021-03-01,NaT,DESCARTADO
...,...,...,...,...,...,...,...,...,...,...,...,...
5495,5496,Masculino,2 meses,Parda,NaN,NaN,NaN,INTERNADO LEITO DE ISOLAMENTO,2020-10-31,2020-11-04,NaT,DESCARTADO
5496,5497,Masculino,79,Parda,NaN,"Doenças Respiratórias Crônicas, Diabetes",EX TABAGISTA,ÓBITO,NaT,2020-12-16,2020-11-19,CONFIRMADO
5497,5498,Masculino,79,Parda,NaN,Doenças Cardíacas ou Vasculares,NaN,INTERNADO LEITO DE ISOLAMENTO,2020-12-14,2020-12-17,NaT,EM ANÁLISE
5498,5499,Masculino,44,Parda,NaN,"Doenças Cardíacas ou Vasculares, Sobrepeso/Obe...",NaN,INTERNADO LEITO DE ISOLAMENTO,2020-11-29,2020-12-01,NaT,DESCARTADO
5499,5500,Masculino,58,Parda,NaN,NaN,HAS,ÓBITO,2020-11-28,2020-12-02,2020-12-08,DESCARTADO

In [18]:
#Alteração do tipo de dados da coluna 'etnia' para 'object'
df["etnia"] = df["etnia"].astype(object)

In [19]:
#Renomear a coluna '_id' para 'id'
df = df.rename(columns={"_id":"id"})

In [20]:
#Checar os tipos de dados
df.dtypes

id                                         int64
sexo                                      object
idade                                     object
raca                                      object
etnia                                     object
morbidades_previas                        object
outras_morbidades_previas                 object
evolucao                                  object
data_inicio_primeiros_sintomas    datetime64[ns]
data_notificacao                  datetime64[ns]
data_obito                        datetime64[ns]
classificacao_final                       object
dtype: object

In [21]:
#Criação de uma nova coluna de idade
df["Idade"] = df["idade"]
df.head(5)

,id,sexo,idade,raca,etnia,morbidades_previas,outras_morbidades_previas,evolucao,data_inicio_primeiros_sintomas,data_notificacao,data_obito,classificacao_final,Idade
0,1,Masculino,9 meses,Ignorado,NaN,Doenças Respiratórias Crônicas,NaN,INTERNADO LEITO DE ISOLAMENTO,2021-02-24,2021-03-02,NaT,DESCARTADO,9 meses
1,2,Feminino,46,Branca,NaN,NaN,NaN,INTERNADO LEITO DE ISOLAMENTO,2021-02-28,2021-03-03,NaT,EM ANÁLISE,46
2,3,Masculino,78,Branca,NaN,"Doenças Cardíacas ou Vasculares, Doença Hepáti...",NaN,ÓBITO,2021-01-06,2021-01-08,2021-01-26,CONFIRMADO,78
3,4,Feminino,62,Parda,NaN,NaN,NaN,INTERNADO LEITO DE ISOLAMENTO,2021-02-23,2021-03-02,NaT,EM ANÁLISE,62
4,5,Masculino,26,Parda,NaN,NaN,NaN,INTERNADO LEITO DE ISOLAMENTO,2021-02-24,2021-03-01,NaT,DESCARTADO,26

In [22]:
#Substituição de idades com menos de 1 ano por 0
filtro = df.Idade.str.contains("mês|meses")
df.loc[filtro, ["Idade"]] = 0

In [23]:
df.head(5)

,id,sexo,idade,raca,etnia,morbidades_previas,outras_morbidades_previas,evolucao,data_inicio_primeiros_sintomas,data_notificacao,data_obito,classificacao_final,Idade
0,1,Masculino,9 meses,Ignorado,NaN,Doenças Respiratórias Crônicas,NaN,INTERNADO LEITO DE ISOLAMENTO,2021-02-24,2021-03-02,NaT,DESCARTADO,0
1,2,Feminino,46,Branca,NaN,NaN,NaN,INTERNADO LEITO DE ISOLAMENTO,2021-02-28,2021-03-03,NaT,EM ANÁLISE,46
2,3,Masculino,78,Branca,NaN,"Doenças Cardíacas ou Vasculares, Doença Hepáti...",NaN,ÓBITO,2021-01-06,2021-01-08,2021-01-26,CONFIRMADO,78
3,4,Feminino,62,Parda,NaN,NaN,NaN,INTERNADO LEITO DE ISOLAMENTO,2021-02-23,2021-03-02,NaT,EM ANÁLISE,62
4,5,Masculino,26,Parda,NaN,NaN,NaN,INTERNADO LEITO DE ISOLAMENTO,2021-02-24,2021-03-01,NaT,DESCARTADO,26

In [24]:
df.loc[df.Idade == "IGN"]

,id,sexo,idade,raca,etnia,morbidades_previas,outras_morbidades_previas,evolucao,data_inicio_primeiros_sintomas,data_notificacao,data_obito,classificacao_final,Idade
2346,2347,Masculino,IGN,NaN,NaN,NaN,NaN,ISOLAMENTO DOMICILIAR,2020-04-21,2020-04-24,NaT,DESCARTADO,IGN
3043,3044,Masculino,IGN,NaN,NaN,NaN,NaN,ISOLAMENTO DOMICILIAR,2020-03-18,2020-03-23,NaT,DESCARTADO,IGN
4188,4189,Feminino,IGN,NaN,NaN,NaN,NaN,ISOLAMENTO DOMICILIAR,2020-03-22,2020-03-24,NaT,INCONCLUSIVO,IGN

In [27]:
#Substituição de dados não informados da coluna 'Idade'
df.loc[df.Idade == "IGN", ["Idade"]] = 999

In [28]:
#Converter a coluna 'idade' para valores inteiros
df["Idade"] = df["Idade"].astype("float").astype("Int64")

In [29]:
#Converter os dados não informados da coluna 'Idade' para nulos
df.loc[df.Idade == 999, ["Idade"]] = pd.NA

In [30]:
df.dtypes

id                                         int64
sexo                                      object
idade                                     object
raca                                      object
etnia                                     object
morbidades_previas                        object
outras_morbidades_previas                 object
evolucao                                  object
data_inicio_primeiros_sintomas    datetime64[ns]
data_notificacao                  datetime64[ns]
data_obito                        datetime64[ns]
classificacao_final                       object
Idade                                      Int64
dtype: object

In [31]:
#Total de dados nulos por coluna
df.isna().sum()

id                                   0
sexo                                 0
idade                                0
raca                              1291
etnia                             5500
morbidades_previas                3689
outras_morbidades_previas         4520
evolucao                           157
data_inicio_primeiros_sintomas     195
data_notificacao                     0
data_obito                        4231
classificacao_final                  0
Idade                                3
dtype: int64

In [33]:
#Validação dos dados
schema = pa.DataFrameSchema(
    columns = {
        "id": pa.Column(pa.Int),
        "sexo": pa.Column(pa.String),
        "idade": pa.Column(pa.String, nullable=True),
        "raca": pa.Column(pa.String, nullable=True),
        "etnia": pa.Column(pa.String, nullable=True),
        "morbidades_previas": pa.Column(pa.String, nullable=True),
        "outras_morbidades_previas": pa.Column(pa.String, nullable=True),
        "evolucao": pa.Column(pa.String, nullable=True),
        "data_inicio_primeiros_sintomas": pa.Column(pa.DateTime, nullable=True),
        "data_notificacao": pa.Column(pa.DateTime),
        "data_obito": pa.Column(pa.DateTime, nullable=True),
        "classificacao_final": pa.Column(pa.String),
        "Idade": pa.Column(pa.Int, nullable=True)
    }
)

In [34]:
schema.validate(df)

,id,sexo,idade,raca,etnia,morbidades_previas,outras_morbidades_previas,evolucao,data_inicio_primeiros_sintomas,data_notificacao,data_obito,classificacao_final,Idade
0,1,Masculino,9 meses,Ignorado,NaN,Doenças Respiratórias Crônicas,NaN,INTERNADO LEITO DE ISOLAMENTO,2021-02-24,2021-03-02,NaT,DESCARTADO,0
1,2,Feminino,46,Branca,NaN,NaN,NaN,INTERNADO LEITO DE ISOLAMENTO,2021-02-28,2021-03-03,NaT,EM ANÁLISE,46
2,3,Masculino,78,Branca,NaN,"Doenças Cardíacas ou Vasculares, Doença Hepáti...",NaN,ÓBITO,2021-01-06,2021-01-08,2021-01-26,CONFIRMADO,78
3,4,Feminino,62,Parda,NaN,NaN,NaN,INTERNADO LEITO DE ISOLAMENTO,2021-02-23,2021-03-02,NaT,EM ANÁLISE,62
4,5,Masculino,26,Parda,NaN,NaN,NaN,INTERNADO LEITO DE ISOLAMENTO,2021-02-24,2021-03-01,NaT,DESCARTADO,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5495,5496,Masculino,2 meses,Parda,NaN,NaN,NaN,INTERNADO LEITO DE ISOLAMENTO,2020-10-31,2020-11-04,NaT,DESCARTADO,0
5496,5497,Masculino,79,Parda,NaN,"Doenças Respiratórias Crônicas, Diabetes",EX TABAGISTA,ÓBITO,NaT,2020-12-16,2020-11-19,CONFIRMADO,79
5497,5498,Masculino,79,Parda,NaN,Doenças Cardíacas ou Vasculares,NaN,INTERNADO LEITO DE ISOLAMENTO,2020-12-14,2020-12-17,NaT,EM ANÁLISE,79
5498,5499,Masculino,44,Parda,NaN,"Doenças Cardíacas ou Vasculares, Sobrepeso/Obe...",NaN,INTERNADO LEITO DE ISOLAMENTO,2020-11-29,2020-12-01,NaT,DESCARTADO,44
5499,5500,Masculino,58,Parda,NaN,NaN,HAS,ÓBITO,2020-11-28,2020-12-02,2020-12-08,DESCARTADO,58